services:
  postgres:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: danny_db
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./initdb ./docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    networks:
      - db-network
    restart: always
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - postgres
    networks:
      - db-network
    restart: always
networks:
  db-network:
volumes:
  pg-data:
name: danny